### PR TITLE
Update operable deps with public versions

### PR DESCRIPTION
**Pull request by sgerrand**
:information_desk_person: The ssh versions of `carrier` and `piper` declared in `mix.exs` require ssh credentials to be available during the dependency update process, which breaks `docker build`.

:memo: Also updated the other declared dependencies using `mix deps.update --all`.

### CODE REVIEW

**Comment by kevsmith** [comment]
@sgerrand You need to update the carrier dep to pick up the new git ref since we merged your PR there.

`mix deps.update carrier` and committing the updated `mix.lock` file should be all we need to merge this.

**Comment by sgerrand** [comment]
@kevsmith: :bow: Done!

**Comment by kevsmith** [comment]
Thanks!

**Comment by sgerrand** [comment]
@kevsmith: Would you please create a new tag (maybe 0.2.1) to encapsulate these changes. :smiley_cat:

**Comment by kevsmith** [comment]
I retagged the merged PR with 0.2. Going forward (especially once we get all the launch announcement stuff done) we'll start incrementing tags.

**Comment by sgerrand** [comment]
@kevsmith: Have you pushed the updated "0.2" tag? It's not in GitHub :point_right: https://github.com/operable/spanner/compare/0.2...master

**Pull request merged**
